CREATE DATABASE IF NOT EXISTS logpress;

USE logpress;

CREATE TABLE IF NOT EXISTS sensors (
    id VARCHAR(36) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    device_id VARCHAR(20) NOT NULL,
    co FLOAT NOT NULL,
    humid FLOAT NOT NULL,
    temp FLOAT NOT NULL,
    lpg FLOAT NOT NULL,
    smoke FLOAT NOT NULL,
    light BOOLEAN NOT NULL,
    motion BOOLEAN NOT NULL,
    PRIMARY KEY(id)
);