CREATE DATABASE IF NOT EXISTS logpress;

USE logpress;

CREATE TABLE IF NOT EXISTS sensors (
    id INT NOT NULL AUTO_INCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    co FLOAT NOT NULL,
    humid FLOAT NOT NULL,
    temp FLOAT NOT NULL,
    lpg FLOAT NOT NULL,
    smoke FLOAT NOT NULL,
    light BOOLEAN NOT NULL,
    motion BOOLEAN NOT NULL,
    PRIMARY KEY(id)
);